### ISSUE TITLE
How do you set the GAIA_TOOLS_DATA Environment Variable on Windows

### ISSUE THREAD

**Issue by d-v-cotton** [jobovy/gaia_tools#29] opened 2020-07-07 05:34 UTC
I am getting the following error: 
'Environment variable `GAIA_TOOLS_DATA` is not set. '
RuntimeError: Environment variable `GAIA_TOOLS_DATA` is not set. This is required to define where the Gaia data are downloaded to. See the readme: https://github.com/jobovy/gaia_tools#data-files-and-environment-variables for more information.

The readme file neatly explains what the environment variable is, but not how to set it. I have tried setting the environment variables through system properties on Windows but without success.

**Comment by jobovy** [comment] 2020-07-07 17:16
Good point that this isn't explained in the README! I think on Windows, this depends on what type of terminal/shell you are using. If you are using the CMD shell, I think you can do
```
set GAIA_TOOLS_DATA=\YOUR\PATH
```
In the Powershell, you'd do
```
$env:GAIA_TOOLS_DATA="\YOUR\PATH"
```

Let me know if this works (and which one you tried) and I can add it to the README.

@henrysky may also be able to help / correct my Windows usage...

**Comment by henrysky** [comment] 2020-07-07 17:28
Those commands only set variable for the lifetime of the CMD shell. The variables will disappear after you closed and then started another shell. You can set permanent environment variable in system properties (attached a screenshot).

![Untitled](https://user-images.githubusercontent.com/28623434/86819282-69eb4180-c055-11ea-92a4-90303eb93a01.png)

Remember you need to restart python and the CMD shell that used to run python/jupyter whatever for such environment variable to take effect.

**Comment by d-v-cotton** [comment] 2020-07-08 00:05
Henry's suggestion worked. In fact this is what I tried the first time, but I required a full system reset rather than just resetting python.

However, I now have a new problem.  I sill cannot download any of the files.

In the process of working through that problem I "solved" another one.

os.errno.ENOENT has been removed in Python 3.7, so I had to edit download.py to remove a reference to it that was prompting the user to check if wget was installed (line 237). I have wget 3.2 installed, however I still get the following error (for example, this is the same no matter which file I attempt to d/l):


Downloading file GaiaSource_1584380076484244352_2200921635402776448.csv.gz ...
C:\Users\dcotton\AppData\Local\Temp\tmpjn2imbxn
Traceback (most recent call last):
  File "U:\poscheck\poscheck_update.py", line 3, in <module>
    tgas_cat = gload.gaiarv()
  File "C:\Users\dcotton\AppData\Roaming\Python\Python37\site-packages\gaia_tools-0.2-py3.7.egg\gaia_tools\load\__init__.py", line 288, in gaiarv
    download.gaiarv(dr=dr)
  File "C:\Users\dcotton\AppData\Roaming\Python\Python37\site-packages\gaia_tools-0.2-py3.7.egg\gaia_tools\load\download.py", line 176, in gaiarv
    _download_file(downloadPath,csvFilePath,verbose=verbose)
  File "C:\Users\dcotton\AppData\Roaming\Python\Python37\site-packages\gaia_tools-0.2-py3.7.egg\gaia_tools\load\download.py", line 225, in _download_file
    subprocess.check_call(cmd)
  File "C:\Program Files\Python37\lib\subprocess.py", line 358, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\Program Files\Python37\lib\subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Program Files\Python37\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files\Python37\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

If I plug the web address of the file directly into a browser then I can d/l it that way, so it's not that the file doesn't exist.

**Comment by jobovy** [comment] 2020-07-08 01:42
Glad that worked! I pushed a fix to the ``errno`` issue. I think the error you are getting is because ``wget`` can't be found; I don't doubt that you have it installed, but it's possible for some reason that it's not accessible to the subprocess spawned by Python. Maybe try
```
import os
os.system('wget')
```
to see whether that can access ``wget``?

As a work-around, you can also figure out the path that the file should have from the routines in ``gaia_tools.load.path`` and then manually download the file and place it there...

**Comment by d-v-cotton** [comment] 2020-07-08 04:43
To get wget to work I had to first install a windows version using the "setup" download, then run the pip install for wget, then double check the path environment variable for the wget exe file. Having done that I can run wget from the command line. I can't establish an SSL connection, but let's not worry about that for the moment.

In trying to run the python program this is the error I get:

Downloading file TgasSource_000-000-000.fits ...
Traceback (most recent call last):
  File "C:\Users\dcotton\AppData\Roaming\Python\Python37\site-packages\gaia_tools-0.2-py3.7.egg\gaia_tools\load\download.py", line 225, in _download_file
    subprocess.check_call(cmd)
  File "C:\Program Files\Python37\lib\subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['wget', 'http://cdn.gea.esac.esa.intGaia\\gdr1\\tgas_source\\fits\\TgasSource_000-000-000.fits', '-O', 'C:\\Users\\dcotton\\AppData\\Local\\Temp\\tmphsnclns3', '--read-timeout=10', '--tries=3']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "U:\poscheck\poscheck_update.py", line 5, in <module>
    tgas_cat = gload.tgas()
  File "C:\Users\dcotton\AppData\Roaming\Python\Python37\site-packages\gaia_tools-0.2-py3.7.egg\gaia_tools\load\__init__.py", line 414, in tgas
    download.tgas(dr=dr)
  File "C:\Users\dcotton\AppData\Roaming\Python\Python37\site-packages\gaia_tools-0.2-py3.7.egg\gaia_tools\load\download.py", line 163, in tgas
    _download_file(downloadPath,filePath,verbose=verbose)
  File "C:\Users\dcotton\AppData\Roaming\Python\Python37\site-packages\gaia_tools-0.2-py3.7.egg\gaia_tools\load\download.py", line 234, in _download_file
    raise IOError('File %s does not appear to exist on the server ...' % (os.path.basename(filePath)))
OSError: File TgasSource_000-000-000.fits does not appear to exist on the server ...

The first problem here is that the joining of paths is entirely wrong.
The program is trying:
wget 'http://cdn.gea.esac.esa.intGaia\\gdr1\\tgas_source\\fits\\TgasSource_000-000-000.fits', '-O', 'C:\\Users\\dcotton\\AppData\\Local\\Temp\\tmphsnclns3'

But what works from the command line is:
wget http://cdn.gea.esac.esa.int/Gaia/gdr1/tgas_source/fits/TgasSource_000-000-000.fits -O C:\Users\dcotton\AppData\Local\Temp\tmphsnclns3

The first / in the web address is missing, and every other slash is the wrong one. I realise that you need a double backslash to get one to come out in a print statement. That might be true here, I'm not sure, but there are obviously other problems before that. (Edit: this comment window has 'helpfully' removed the double slashes.)

As this is the very first 2-line example program in the documentation, this makes me think this has never been tested on a Windows machine. Rather than be the person who debugs it, I think I will use my personal Mac for this job instead of the windows machine my employer has supplied me for the task.

Might I suggest that a disclaimer be added to the code that it hasn't been tested on Windows?

**Comment by jobovy** [comment] 2020-07-08 14:32
Yes, I see why the URL has the wrong format, it's because its created from the path on Windows which are backslashes instead of forward slashes. After fixing that, it seems like things should probably work now, given that it seems like you figured out how to have ``wget`` run.

Yes, it's probably true that the code has not been used much on Windows. Please remember that this is research software provided with no guarantees that it will work on any particular machine and where support is provided on a best-effort basis. The tone of your comment is such that you seem to expect that a code like this should work on Windows, but most people don't use Windows for research in astrophysics and supporting it is therefore not very high on most people's list of priorities (Windows users will typically use a Linux VM or similar emulator, or nowadays the WSL). Also note that this is a public code repository; you are more than welcome to make the changes required to get this code to work on Windows and submit a pull request. Given that it seems like you are not going to be using Windows, I'm not going to make further changes here.

GitHub comments are pretty standard Markdown, so you can use Markdown commands to paste code and code output, thus not losing backslashes for example.

**Comment by d-v-cotton** [comment] 2020-07-08 21:25
@jobovy Sincerely, thank you for your efforts. My comments are meant to be taken literally. i.e. I was (i) actually suggesting the disclaimer, and (ii) letting you know I am going to take a different approach, so as to unburden you from any perceived obligation to fix the issues in any hurry.

I'm aware that most people will use a linux (or Mac) based system for astrophysics research, but python is sold as (so to speak) having equal functionality across systems. This is shy I suggest the disclaimer, to reduce the expectations of the user in this regard.

**Comment by jobovy** [comment] 2020-07-09 00:55
Thanks, I appreciate it! I'm reluctant to put too much of a disclaimer, because I think that with small tweaks to the code, people could use it on Windows if they had to (like the issues you are having can be pretty easily fixed), so I don't want to completely put off Windows users from even considering the code. But I see your point that it's frustrating to come upon a code that doesn't just work out-of-the-box on Windows. Part of the issue is that's it's difficult to write automated tests for data-handling packages, because they would always have to download the rather large data files, so it's hard to automatically test that the code runs on Windows (which I do do for some of my other projects, like ``galpy``). So I'll leave this open until I add something to the README.

**Closed as completed** 2020-07-09 14:18 UTC
